### ISSUE TITLE
Allow to register contacts

### ISSUE THREAD

**Issue by LucileDT** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/structura-2#8]
# Context

Non profits often are in contact with people and organizations. We need to save them to easily access their information when needed.

# Todo
- [ ] save "contacts" information
  - [ ] fields:
    - [ ] abstract getName()
    - [ ] address
    - [ ] phoneNumber
    - [ ] email address
  - [ ] save natural persons information
    - [ ] firstname
    - [ ] lastname
    - [ ] mobilePhoneNumber
  - [ ] save companies information
    - [ ] name
    - [ ] siret
  - [ ] save non profits information
    - [ ] name
    - [ ] website
- [ ] have a list of "contacts"
