### ISSUE TITLE
Add filters on contact list

### ISSUE THREAD

**Issue by LucileDT** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/structura-2#9]
# Context

To search through Structura contacts, we need filters.

# Todo
- [ ] add general search bar
- [ ] add filters on entityType
  - [ ] people
  - [ ] company
  - [ ] association
- [ ] postal code (département)
- [ ] name
- [ ] phone number
- [ ] email
